version: '3.8'

services:
  rest-catalog:
    image: tabulario/iceberg-rest-catalog:latest
    container_name: iceberg-rest-catalog
    ports:
      - "8181:8181"
    environment:
      - CATALOG_WAREHOUSE=s3://iceberg-data
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH_STYLE_ACCESS=true
      - CATALOG_S3_ACCESS_KEY_ID=minioadmin
      - CATALOG_S3_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      - minio
    networks:
      - iceberg-network

  minio:
    image: minio/minio:latest
    container_name: iceberg-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - iceberg-network

  # Optional: MinIO client for easy data management
  mc:
    image: minio/mc:latest
    container_name: iceberg-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/iceberg-data;
      exit 0;
      "
    networks:
      - iceberg-network

volumes:
  minio_data:

networks:
  iceberg-network:
    driver: bridge